site_name: CAPJU DOCS

theme:
  name: material
  palette:
    primary: black
    accent: teal
  font:
    text: Roboto
  language: pt
  logo: https://capju.netlify.app/assets/logo.png
  favicon: https://capju.netlify.app/assets/logo.png
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

nav:
  - Sobre: index.md
  - Manual de Instalação: manual_de_instalacao.md
  - Guias:
      - Politica de Contribuição: politica_de_contribuicao.md
  - Planejamento:
      - Planejamento: planejamento.md
      - Quadro de conhecimento: Controle/quadro_de_conhecimento.md
      - Quadro de disponibilidade: Controle/quadro_de_disponibilidade.md
      - Quadro de pareamento: Controle/quadro_de_pareamento.md
      - Cronograma de dojo: Controle/cronograma_de_dojo.md
      - Plano de qualidade: Planejamento/qualidade.md
  - Produto:
      - Visão do Produto: VisaoProduto/visao_do_produto.md
      - Backlog do Produto: backlog_do_produto.md
      - Protótipo: prototipo.md
  - Comunicação:
      - Comunicação do time: comunicacao.md
      - Rituais da Equipe:  rituais.md
      - Guia do Facilitador: facilitador.md
      - Relatório de Eventos: 
        - Semana 1: Relatórios/semana1.md
        - Semana 2: Relatórios/semana2.md
        - Semana 3: Relatórios/semana3.md
        - Semana 4: Relatórios/semana4.md
        - Semana 5: Relatórios/semana5.md
        - Semana 6: Relatórios/semana6.md
        - Sprint 1: Relatórios/sprint1.md
        - Sprint 2: Relatórios/sprint2.md
        - Sprint 3: Relatórios/sprint3.md
        - Sprint 4: Relatórios/sprint4.md
        - Sprint 5: Relatórios/sprint5.md
        - Sprint 6: Relatórios/sprint6.md
        - Sprint 7: Relatórios/sprint7.md
      - Ferramentas Utilizadas: ferramentas_utilizadas_pela_equipe.md
  - Gestão do Projeto:
      - EAP: estrutura_analitica_do_projeto.md
      - Estimativa de Custos: custos.md
      - Gerenciamento de Riscos: plano_de_gerenciamento_de_riscos.md
      - DAS: DAS/documento_de_arquitetura.md
  - Relatorio de Encerramento do Projeto: 
      - Planejado Vs Executado: RelatorioEncerramentoDoProjeto/planejado_vs_executado.md
      - Proximos passos: RelatorioEncerramentoDoProjeto/proximos-passos.md
