site_name: CAPJU DOCS

theme:
    name: material
    language: pt
    logo: https://capju.netlify.app/assets/logo.png
    favicon: https://capju.netlify.app/assets/logo.png

nav:
    - Sobre: index.md
    - Politica de Contribuição: politica_de_contribuicao.md
    - Planejamento de Custos: custos.md
    - Relatório de Eventos: Relatórios/relatorios_do_projeto.md
    - EAP : estrutura_analitica_do_projeto.md
    - Backlog do Produto : backlog_do_produto.md
    - Visão do Produto: VisaoProduto/visao_do_produto.md
    - DAS: DAS/documento_de_arquitetura.md
    - Planejamento: planejamento.md
    - Controle da equipe: 
        - Quadro de conhecimento: Controle/quadro_de_conhecimento.md
        - Quadro de disponibilidade: Controle/quadro_de_disponibilidade.md
        - Quadro de pareamento: Controle/quadro_de_pareamento.md
        - Cronograma de dojo: Controle/cronograma_de_dojo.md
        - Plano de gerenciamento de riscos: plano_de_gerenciamento_de_riscos.md
        - Comunicação do time: comunicacao.md
        - Ferramentas utilizadas pela equipe: ferramentas_utilizadas_pela_equipe.md


