site_name: CAPJU DOCS

theme:
    name: material
    language: pt
    logo: https://capju.netlify.app/logo.png
    favicon: https://capju.netlify.app/logo.png

nav:
    - Sobre: index.md
    - Politica de Contribuição: politica_de_contribuicao.md
    - Relatório de Eventos: Relatórios/relatorios_do_projeto.md
    - EAP : estrutura_analitica_do_projeto.md
    - Visão do Produto: VisaoProduto/visao_do_produto.md
